### ISSUE TITLE
OOM error when image is captured multiple time

### ISSUE THREAD

**Issue by mandevur** [HorizonCamera/HorizonSDK-Android#2]
java.lang.OutOfMemoryError: Failed to allocate a 38280012 byte allocation with 11184936 free bytes and 10MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at com.hvt.horizonSDK.Utils.BitmapUtils.levelBitmap(SourceFile:253)
	at com.hvt.horizonSDK.CameraEncoder$1$1.run(SourceFile:398)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Petrakeas** [comment]
The `OutOfMemoryError` was thrown because Horizon SDK couldn't allocate enough memory to perform bitmap operations when capturing a photo.

After dbdb304  , Horizon SDK will catch the `OutOfMemoryError`  and not let the app crash. `onPhotoCaptured()` will be called, but `success` will be false since capturing failed.

The cause of the error though is that your app didn't have enough memory. Horizon SDK doesn't cause any memory leaks. So, the problem may be on your side. Make sure that you recycle any bitmaps that are not used.
